### ISSUE TITLE
Doesn't work with OPML file exported from Pocket Casts

### ISSUE THREAD

**Issue by bgiesing** [elliotwms/opml-to-spotify#13]
```
Searching for 1 shows
Searching for
panic: No search query

goroutine 1 [running]:
github.com/elliotwms/opml-to-spotify/cmd.run(0xe6bbc0, {0x1204f560, 0x1, 0x3})
        /github/workspace/cmd/import.go:59 +0x419
github.com/spf13/cobra.(*Command).execute(0xe6bbc0, {0x1204f548, 0x3, 0x3})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x665
github.com/spf13/cobra.(*Command).ExecuteC(0xe6bd20)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x406
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/elliotwms/opml-to-spotify/cmd.Execute()
        /github/workspace/cmd/root.go:20 +0x23
main.main()
        /github/workspace/main.go:6 +0x17
```

Version 1.0.2 on Windows 11

Export from Spotify worked but import doesn't, OPML imports fine into another podcast client on Windows (Grover Podcast) and exporting back out from Grover then using that for opml-to-spotify works

**Comment by elliotwms** [comment]
Hi! Thanks for the report. I'm not familiar with Pocket Casts, do you have a sample OPML file you're able to share?

**Comment by bgiesing** [comment]
My OPML has a bunch of private feeds so if there's some way I can send you mine privately that could work

Either that or Pocket Casts is free to use so you might be able to sign up yourself but no idea if the issue would be replicatable if it's not the exact same shows. https://pocketcasts.com/
